### ISSUE TITLE
Bad Certificate error

### ISSUE THREAD

**Issue by monikaq4udev** [odyshewroman/AndroidTVRemoteControl#4]
Description:
I am getting bad certificate or unknown certificate error while connecting the android tv from iPhone. Please find the below error logs.

Logs:

2023-10-27 11:02:10.793142+0530 Demo[7026:4165378] [boringssl] boringssl_context_handle_fatal_alert(1967) [C4:1][0x149f195a0] read alert, level: fatal, description: certificate unknown
2023-10-27 11:02:10.794360+0530 Demo[7026:4165378] [connection] nw_read_request_report [C4] Receive failed with error "misc. bad certificate"
2023-10-27 11:02:10.794555+0530 Demo[7026:4165378] [boringssl] boringssl_session_handshake_error_print(41) [C4:1][0x149f195a0] Error: 5533447048:error:10000416:SSL routines:OPENSSL_internal:SSLV3_ALERT_CERTIFICATE_UNKNOWN:/Library/Caches/com.apple.xbs/Sources/boringssl/ssl/tls_record.cc:594:SSL alert number 46

Also, please share the detail of how to create a certificate for establish TLS connection.

**Comment by odyshewroman** [comment]
Am I understanding correctly that the example works for the simulator but not with a real device? 
If you set a debug breakpoint in the TLSManager inside the sec_protocol_options_set_verify_block block, does the code execute there during the connection setup?

**Comment by odyshewroman** [comment]
At the first launch, such errors in the log are possible, it's normal and does not lead to the application crashing. I may have complicated the example, but I wanted to demonstrate the possibility that it's not necessary to enter the code from the TV screen each time for pairing. To achieve this, I firstly attempt to connect to the device. During the first attempt, a connection timeout error will be caught (at this point, you receive a log with errors), and the code branch for pairing and code input will be executed. After a successful pairing, subsequent launches will connect to your device without entering the code.

I have also fixed some errors related to parsing responses from the Android TV OS. Please try to update and run the example again.

**Comment by thachonline** [comment]
@odyshewroman ody
Is there any way I can remove the certificate from my Android TV device?
In the case of the bad certificate, I tried to delete it from the app and from the Android TV device, but unfortunately I couldn't find any way to delete it.
That is, in debug mode, is there any way I can control the pair code display from Android TV?

**Comment by monikaq4udev** [comment]
@odyshewroman ody
I have run the updated code but still facing the same error while connecting with the Android TV.  Also, facing same issue in simulator as well. 

I have set a breakpoint inside the sec_protocol_options_set_verify_block block, it's executed during connection. The problem with the self-signed certificate which used for TLS connection. 

Are you able to setup the connection and get the pair code in the Android TV with these certificates ?

**Comment by odyshewroman** [comment]
@thachonline I don't know how to remove a certificate on an Android TV device. And I don't understand the reason behind this action, why would I need to?

@monikaq4udev It's very strange; I've worked with many devices on Android TV OS, and I've never encountered such an issue. The connection has always been established with a self-signed certificate (except in cases where the device lacks a certificate or in situations where the device has a clean Android instead of Android TV). I've checked the functionality of the current certificate in the project and a newly created one, both on the emulator and on a real device, and everything works for me. Could you please share the name and model of the Android TV OS device you're trying to establish a connection with?

**Comment by monikaq4udev** [comment]
@odyshewroman 
Android TV name - Acer & os version - android 11 
iPhone os - 16.1.1

**Comment by odyshewroman** [comment]
@monikaq4udev Can you verify that your TV has a certificate?
just running from terminal `openssl s_client -connect <SMART_TV_IP>:6467 -prexit -state -debug`
or download certificate `openssl s_client -showcerts -connect <SMART_TV_IP>:6467 </dev/null 2>/dev/null|openssl x509 -outform PEM > server.pem`

**Comment by monikaq4udev** [comment]
@odyshewroman Yes, my TV has a certificate. I have downloaded certificate using the above openssl command.

**Comment by monikaq4udev** [comment]
@odyshewroman I have made some changes in setup connection code and it's working now. I am able to get the pairing code.

But i want to create a certificate using code instead of static file. Can you please share the info of creating the self-signed certificate through code ?

**Comment by odyshewroman** [comment]
@monikaq4udev Could you please share what changes helped in your case? Maybe I should add them to the project.

To be honest, I don't know how to generate a certificate from the code; it's not within the functionality of this library. As I mentioned earlier, the library is responsible for connecting to Android TV OS and sending data. How you create or obtain the certificate is your own responsibility.

**Comment by monikaq4udev** [comment]
@odyshewroman I have saved the certificate in the keychain and get from the keychain to establish the connection. I will be share the code through email.

**Comment by floriangbh** [comment]
@monikaq4udev maybe you can share the code? 
I'm also interested (and maybe other people in the future :) )

**Comment by monikaq4udev** [comment]
@odyshewroman @floriangbh, I have saved the identity from client certificate in the keychain in cert function in CertManager class and get the same identity from keychain and pass this client identity as param in getNWParams function in TLSManager. Please find the screenshot and code changes.

[Archive.zip](https://github.com/odyshewroman/AndroidTVRemoteControl/files/13266932/Archive.zip)

**Comment by monikaq4udev** [comment]
@odyshewroman @floriangbh, I have saved the identity from client certificate in the keychain in cert function in CertManager class and get the same identity from keychain and pass this client identity as param in getNWParams function in TLSManager. Please find the screenshot and code changes.

[Archive.zip](https://github.com/odyshewroman/AndroidTVRemoteControl/files/13266932/Archive.zip)

**Comment by monikaq4udev** [comment]
@odyshewroman @floriangbh, I have saved the identity from client certificate in the keychain in cert function in CertManager class and get the same identity from keychain and pass this client identity as param in getNWParams function in TLSManager. Please find the screenshot and code changes.

[Archive.zip](https://github.com/odyshewroman/AndroidTVRemoteControl/files/13266932/Archive.zip)

**Comment by monikaq4udev** [comment]
@odyshewroman @floriangbh, I have saved the identity from client certificate in the keychain in cert function in CertManager class and get the same identity from keychain and pass this client identity as param in getNWParams function in TLSManager. Please find the screenshot and code changes.

[Archive.zip](https://github.com/odyshewroman/AndroidTVRemoteControl/files/13266932/Archive.zip)
