### ISSUE TITLE
Connection reset by peer after sometime 

### ISSUE THREAD

**Issue by Goule** [odyshewroman/AndroidTVRemoteControl#8]
Hello, 

I've had some trouble with the connection with the TV. 
After 30 seconds of inactivity (=without sending any key), the TV reset the connection if I try to send another command. 

To reproduce it : 
- Take the demo project
- Connect to a TV
- Press VOL UP/DOWN : OK 
- Wait 30 seconds 
- Press VOL UP/DOWN -> `AndroidTVRemoteControlError.connectionFailed(POSIXErrorCode(rawValue: 54): Connection reset by peer)`

Look like the socket is closed, I didn't find why yet !

**Comment by odyshewroman** [comment]
@Goule, I have fixed it in new version 1.2.1, please check it.

**Comment by Goule** [comment]
Hello @odyshewroman ! 

Thanks for the update. I have the same issue even with the ping pong fix :(

**Comment by odyshewroman** [comment]
@Goule, thanks for checking. Indeed still have same issue, it's ping problem, for some reason my AndroidTV Box send invalid ping package for Demo project and I can't reply, but for my another project same TV Box have sent valid ping.
I trying to figure out the reason of this cases.

**Comment by odyshewroman** [comment]
@Goule, my bad. Have fixed ping issue, please try v1.2.2

**Comment by Goule** [comment]
Hello @odyshewroman , 

Thanks for the update ! 

Still the same issue, but different error : 

<img width="1585" alt="Screenshot 2023-11-17 at 09 06 55" src="https://github.com/odyshewroman/AndroidTVRemoteControl/assets/21126201/76a23f9c-0f8a-4c0b-9039-7c07b9c21e76">

Look like the ping pong message isn't well handled 🤔

**Comment by odyshewroman** [comment]
@Goule one more time, please.

**Comment by Goule** [comment]
Hello ! 

<img width="1851" alt="Screenshot 2023-11-17 at 19 23 36" src="https://github.com/odyshewroman/AndroidTVRemoteControl/assets/21126201/b132eacc-223d-49dc-a3f8-bd90899bf8c2">

Another issue with a crash 🤔

**Comment by odyshewroman** [comment]
@Goule , interesting case, how long time it was working before you catch this crash? I am curious about data of this ping. In anyway, I made one more fix 🤦‍♂️

**Comment by Goule** [comment]
Generally the crash appear in some seconds ! It's very fast on my TV ! 

I've tested, the crash is gone but the disconnection appear again : 

<img width="1438" alt="Screenshot 2023-11-18 at 17 45 54" src="https://github.com/odyshewroman/AndroidTVRemoteControl/assets/21126201/c7abd194-a12f-4d97-822a-cfc635e10ee5">

Look like the ping pong work well after the pairing, but after some command has been sent, the pong isn't sent anymore to the TV, so the connection is closed ?

**Comment by odyshewroman** [comment]
@Goule  I think, the problem is that TV send ping that I can't recognize, so I not send the pong, that leads to closing connect from TV side.
Can you add log the data before trying cast to ping, on the first line of handlePing function, for check it.

**Comment by Goule** [comment]
I've added a print in the `handleData` with `print("handleData with data : \(data.description.utf8) : \(data as NSData)")`

Here is the result : 

<img width="1439" alt="Screenshot 2023-11-19 at 07 49 49" src="https://github.com/odyshewroman/AndroidTVRemoteControl/assets/21126201/d1e34a93-dcda-41b7-99f2-ca02f9917019">

The ping is with 9 bytes. 

But after the volUp(), there is no 9 bytes messages, only message which increase their size each time

**Comment by odyshewroman** [comment]
Thanks for data. Hmm... But in some reason the TV send again the data which come after sending 2nd config message, idk why...

**Comment by odyshewroman** [comment]
@Goule I will create a branch to try to resolve the issue in your case, but I can't reproduce this problem on my device. Please send me an email at [odyshewroman@gmail.com](mailto:odyshewroman@gmail.com), as I have a channel to send you a quick fix.

**Comment by Goule** [comment]
Hello, 

Here is some additional context : 

connectionPrepairing connection Prepairing
connected connected
handleData with data : [89, 10, 87, 8, 255, 4, 18, 82, 10, 8, 65, 105, 80, 108, 117, 115, 50, 75, 18, 11, 69, 120, 112, 114, 101, 115, 115, 108, 117, 99, 107, 24, 1, 34, 2, 49, 49, 42, 36, 99, 111, 109, 46, 103, 111, 111, 103, 108, 101, 46, 97, 110, 100, 114, 111, 105, 100, 46, 116, 118, 46, 114, 101, 109, 111, 116, 101, 46, 115, 101, 114, 118, 105, 99, 101, 50, 13, 53, 46, 50, 46, 52, 55, 51, 50, 53, 52, 49, 51, 51]
fisrtConfigMessageReceived(Demo.CommandNetwork.DeviceInfo(model: "AiPlus2K", vendor: "Expressluck", version: "11", appName: "com.google.android.tv.remote.service", appBuild: "5.2.473254133")) fisrt Config Message Received: vendor: Expressluck model: AiPlus2K
firstConfigSent first Config Sent
handleData with data : [2, 18, 0]
secondConfigSent second Config Sent
handleData with data : [27, 146, 3, 24, 8, 2, 16, 2, 26]
handleData with data : [27, 146, 3, 24, 8, 2, 16, 2, 26, 8, 65, 105, 80, 108, 117, 115, 50, 75, 32, 2, 40, 0, 48, 100, 56, 73, 64, 0]
handleData with data : [5, 194, 2, 2, 8, 1]
handleData with data : [34, 162, 1, 31, 10, 29, 98, 27, 99, 111, 109, 46, 103, 111, 111, 103, 108, 101, 46, 97, 110, 100, 114, 111, 105, 100, 46, 98, 97, 99, 107, 100, 114, 111, 112]
paired(runningApp: Optional("com.google.android.backdrop")) Paired! Current runned app com.google.android.backdrop
handleData with data : [8, 66, 6, 8, 1, 16, 200, 216, 27]
handleData with data : [8, 66, 6]
handleData with data : [8, 66, 6, 8, 2, 16, 220, 255, 27]
volUp()
handleData with data : [27, 146, 3, 24, 8, 2, 16, 2, 26, 8, 65, 105, 80, 108, 117, 115, 50, 75, 32, 2, 40, 0, 48, 100, 56, 74, 64, 0]
handleData with data : [27, 146, 3, 24, 8, 2, 16, 2, 26, 8, 65, 105, 80, 108, 117, 115, 50, 75, 32, 2, 40, 0, 48, 100, 56, 74, 64, 0, 8, 66, 6]
handleData with data : [27, 146, 3, 24, 8, 2, 16, 2, 26, 8, 65, 105, 80, 108, 117, 115, 50, 75, 32, 2, 40, 0, 48, 100, 56, 74, 64, 0, 8, 66, 6, 8, 3]
handleData with data : [27, 146, 3, 24, 8, 2, 16, 2, 26, 8, 65, 105, 80, 108, 117, 115, 50, 75, 32, 2, 40, 0, 48, 100, 56, 74, 64, 0, 8, 66, 6, 8, 3, 16, 216, 176, 28]
handleData with data : [27, 146, 3, 24, 8, 2, 16, 2, 26, 8, 65, 105, 80, 108, 117, 115, 50, 75, 32, 2, 40, 0, 48, 100, 56, 74, 64, 0, 8, 66, 6, 8, 3, 16, 216, 176, 28, 8, 66, 6]
handleData with data : [27, 146, 3, 24, 8, 2, 16, 2, 26, 8, 65, 105, 80, 108, 117, 115, 50, 75, 32, 2, 40, 0, 48, 100, 56, 74, 64, 0, 8, 66, 6, 8, 3, 16, 216, 176, 28, 8, 66, 6, 8, 4, 16, 193, 227, 28]
handleData with data : [27, 146, 3, 24, 8, 2, 16, 2, 26, 8, 65, 105, 80, 108, 117, 115, 50, 75, 32, 2, 40, 0, 48, 100, 56, 74, 64, 0, 8, 66, 6, 8, 3, 16, 216, 176, 28, 8, 66, 6, 8, 4, 16, 193, 227, 28, 8, 66, 6, 8, 5, 16, 172, 150, 29]
error(Demo.AndroidTVRemoteControlError.receiveDataError(POSIXErrorCode(rawValue: 96): No message available on STREAM)) Error: receive Data Error
nw_flow_add_read_request [C1 192.168.0.186:6466 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0[802.11], ipv4, dns, uses wifi)] already delivered final read, cannot accept read requests
nw_read_request_report [C1] Receive failed with error "No message available on STREAM"

I've also changed case .sceondConfigSent: to  case .sceondConfigSent, .paired:.

Thanks !

**Comment by monikaq4udev** [comment]
@Goule @odyshewroman 
I am facing the same issue "connection reset by peer after sometime". I have implemented the latest V2 code also but still getting the issue. Please help me to fix this.

**Comment by odyshewroman** [comment]
@monikaq4udev need logs of ping\pongs maybe there is a case when I can't recognise ping and reply pong message, in this case device will disconnected after 15 seconds

**Comment by monikaq4udev** [comment]
@odyshewroman please find the logs of data send and receive before disconnecting

handleData with data 77 bytes
Connection 1 bytes Optional(Network.NWConnection.State.ready)
remoteState firstConfigSent FirstConfigurationRequest(deviceInfo: TvRemote.CommandNetwork.DeviceInfo(model: "client", vendor: "iPhone", version: "1.0.0", appName: "RemoteApp", appBuild: "235"))
Connection 48 bytes Optional(Network.NWConnection.State.ready)
connection did send, data: {length = 1, bytes = 0x30}
connection did send, data: {length = 48, bytes = 0x0a2e08ee 0412290a 06636c69 656e7412 ... 70320531 2e302e30 }
handleData with data 3 bytes
Connection 1 bytes Optional(Network.NWConnection.State.ready)
remoteState secondConfigSent SecondConfigurationRequest(data: 5 bytes)
Connection 5 bytes Optional(Network.NWConnection.State.ready)
connection did send, data: {length = 1, bytes = 0x05}
connection did send, data: {length = 5, bytes = 0x120308ee04}
handleData with data 22 bytes
handleData with data 6 bytes
handleData with data 35 bytes
remoteState paired runningApp Optional("com.google.android.backdrop")
Connection 1 bytes Optional(Network.NWConnection.State.ready)
Connection 6 bytes Optional(Network.NWConnection.State.ready)
connection did send, data: {length = 1, bytes = 0x06}
connection did send, data: {length = 6, bytes = 0x520408031003}
2023-12-04 14:11:20.330132+0530 TvRemote[67041:2540696] [tcp] tcp_input [C1:2] flags=[R] seq=3834101755, ack=0, win=0 state=CLOSE_WAIT rcv_nxt=3834101755, snd_una=2380209552
Error POSIXErrorCode(rawValue: 54): Connection reset by peer
Error: connection Failed

**Comment by odyshewroman** [comment]
@monikaq4udev thanks, but logs of received data are needed.
There is a log - '_handleData with data 12 bytes_,' but it is necessary to understand what is contained there. You can get this data for logs as byte Array - like: `print(Array(self.data))`
Also, I do not understand what the last 2 sent commands represent; it seems to be the sending of commands for pressing 'PAD_UP' and 'HOME,' but this is not present in the Demo implementation.
